krakend: krakend run -c etc/krakend.json --port $PORT
auth_api: uvicorn --port $PORT auth_api:app --reload

primary: bin/litefs mount -config etc/primary.yml
secondary_1: bin/litefs mount -config etc/secondary_1.yml
secondary_2: bin/litefs mount -config etc/secondary_2.yml

# enrollment_api_1: uvicorn --port $PORT enrollment_api:app --reload
# enrollment_api_2: uvicorn --port $PORT enrollment_api:app --reload
# enrollment_api_3: uvicorn --port $PORT enrollment_api:app --reload