krakend: krakend run -c etc/krakend.json --port $PORT
enrollment_api: uvicorn --port $PORT enrollment_api:app --reload

primary: bin/litefs mount -config etc/primary.yml
secondary_1: bin/litefs mount -config etc/secondary_1.yml
secondary_2: bin/litefs mount -config etc/secondary_2.yml